# Generated by Django 2.2.2 on 2022-01-06 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=20, verbose_name='課題名')),
                ('task_subject', models.CharField(max_length=20, verbose_name='教科')),
                ('task_status', models.CharField(max_length=3, verbose_name='状態')),
                ('task_create_date', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('task_update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('task_created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('task_school', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='accounts.School', verbose_name='学校')),
            ],
            options={
                'verbose_name_plural': 'Task',
            },
        ),
    ]
