# Generated by Django 2.2.2 on 2022-01-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('0', '非公開'), ('1', '公開')], default='0', max_length=1, verbose_name='状態'),
        ),
    ]
