# Generated by Django 2.2.2 on 2022-01-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220106_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_score',
            field=models.IntegerField(default=100, verbose_name='総得点'),
        ),
    ]
