# Generated by Django 2.2.2 on 2022-01-12 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20220110_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q_task',
        ),
        migrations.AddField(
            model_name='question',
            name='q_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='task.Task', verbose_name='課題'),
        ),
    ]
