# Generated by Django 2.2.2 on 2022-01-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20220112_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q_task',
        ),
        migrations.AddField(
            model_name='question',
            name='q_task',
            field=models.ManyToManyField(to='task.Task'),
        ),
    ]
