# Generated by Django 2.2.2 on 2022-01-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20220112_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_answer',
            field=models.CharField(max_length=200, verbose_name='解答'),
        ),
    ]
