# Generated by Django 2.2.2 on 2022-01-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20220112_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_statement',
            field=models.TextField(blank=True, null=True, verbose_name='問題文'),
        ),
    ]
