# Generated by Django 2.2.2 on 2022-01-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20220113_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_time',
            field=models.IntegerField(default=60, verbose_name='課題時間'),
        ),
    ]
