# Generated by Django 2.2.2 on 2022-01-21 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('task', '0009_task_task_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribute_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Class', verbose_name='クラス')),
                ('distribute_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.Task', verbose_name='課題')),
            ],
        ),
    ]
