# Generated by Django 2.2.2 on 2021-11-25 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='学年')),
                ('name', models.CharField(max_length=10, verbose_name='クラス名')),
                ('school', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='task.School', verbose_name='学校')),
            ],
        ),
    ]
