# Generated by Django 2.2.2 on 2021-11-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Class'},
        ),
    ]
